{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "import logging\n",
    "import GPy\n",
    "import GPyOpt\n",
    "import matplotlib.pyplot as plt\n",
    "plt.switch_backend('agg')\n",
    "\n",
    "from training_util import *\n",
    "\n",
    "#choose model to be trained\n",
    "enzyme = 'esp'\n",
    "\n",
    "# create logger with 'Model_application'\n",
    "logger = logging.getLogger('Model')\n",
    "logger.setLevel(logging.DEBUG)\n",
    "# create file handler which logs even debug messages\n",
    "fh = logging.FileHandler(enzyme + '_RNN_biofeat.log')\n",
    "fh.setLevel(logging.DEBUG)\n",
    "# create formatter and add it to the handlers\n",
    "formatter = logging.Formatter('%(asctime)s - %(name)s - %(levelname)s - %(message)s')\n",
    "fh.setFormatter(formatter)\n",
    "logger.addHandler(fh)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [],
   "source": [
    "#string parameters changed to dictionary which keys are integers\n",
    "fc_activation_dict = {'1':'relu','2':'tanh', '3':'sigmoid', '4':'hard_sigmoid', '0':'elu'}\n",
    "initializer_dict = {'1':'lecun_uniform','2':'normal', '3':'he_normal', '0':'he_uniform'}\n",
    "optimizer_dict = {'1':SGD,'2':RMSprop, '3':Adagrad, '4':Adadelta,'5':Adam,'6':Adamax,'0':Nadam}\n",
    "#parameter space\n",
    "bounds = [\n",
    "          #Discrete  \n",
    "          {'name':'em_drop','type':'discrete','domain':(0.1,0.2,0.3)},\n",
    "          {'name':'rnn_drop','type':'discrete','domain':(0.1,0.2,0.4,0.4,0.5,0.6,0.7)},\n",
    "          {'name':'rnn_rec_drop','type':'discrete','domain':(0.1,0.2,0.4,0.4,0.5,0.6,0.7)},\n",
    "          {'name':'fc_drop','type':'discrete','domain':(0.1,0.2,0.4,0.4,0.5,0.6,0.7)},\n",
    "          #Discrete\n",
    "          {'name':'batch_size', 'type': 'discrete','domain': (20,30, 40, 50,60, 70, 80,90, 100)},\n",
    "          {'name':'epochs', 'type': 'discrete','domain': (20, 25, 30, 35, 40, 45, 50, 55)},\n",
    "          {'name':'em_dim', 'type': 'discrete','domain': (16, 20, 24, 28, 32, 36, 40, 44, 48, 52, 56, 60, 64, 68)},\n",
    "          {'name':'rnn_units', 'type': 'discrete','domain': (20, 30, 40, 50, 60, 70, 80, 90, 100, 120, 140, 160, 180, 200, 220, 240)},\n",
    "          {'name':'fc_num_hidden_layers', 'type': 'discrete','domain': (1,2,3,4,5,6)},\n",
    "          {'name':'fc_num_units', 'type': 'discrete','domain': (50, 60, 70,80, 90, 100, 120, 140, 160, 180, 200, 220, 240, 260, 280, 300, 320, 340, 360, 380, 400)},\n",
    "          #Categorical\n",
    "          {'name':'fc_activation', 'type': 'categorical','domain':tuple(map(int,tuple(fc_activation_dict.keys())))},\n",
    "          {'name':'optimizer', 'type': 'categorical','domain':tuple(map(int,tuple(optimizer_dict.keys())))}\n",
    "         ]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {},
   "outputs": [],
   "source": [
    "from dotmap import DotMap\n",
    "def cat_decode(x):\n",
    "    opt= DotMap()\n",
    "    opt.em_drop = float(x[:, 0])\n",
    "    opt.rnn_drop = float(x[:, 1])\n",
    "    opt.rnn_rec_drop = float(x[:, 2])\n",
    "    opt.fc_drop = float(x[:, 3])\n",
    "    \n",
    "    opt.batch_size = int(x[:, 4])\n",
    "    opt.epochs = int(x[:, 5]) \n",
    "    opt.em_dim =int(x[:, 6])\n",
    "    opt.rnn_units = int(x[:, 7])\n",
    "    opt.fc_num_hidden_layers = int(x[:, 8]) \n",
    "    opt.fc_num_units = int(x[:, 9])\n",
    "    \n",
    "    opt.fc_activation = int(x[:,10])\n",
    "    opt.optimizer = int(x[:,11])\n",
    "    return opt\n",
    "    \n",
    "\n",
    "def f(x):\n",
    "    opt = cat_decode(x)\n",
    "    param = {'model_type':enzyme,#mannualy set model_type as enzyme\n",
    "            'em_drop':opt.em_drop,\n",
    "           'rnn_drop':opt.rnn_drop,\n",
    "           'rnn_rec_drop':opt.rnn_rec_drop,\n",
    "           'fc_drop':opt.fc_drop,\n",
    "\n",
    "           'batch_size':opt.batch_size,\n",
    "           'epochs':opt.epochs, \n",
    "           'em_dim':opt.em_dim,\n",
    "           'rnn_units':opt.rnn_units, \n",
    "           'fc_num_hidden_layers':opt.fc_num_hidden_layers, \n",
    "           'fc_num_units':opt.fc_num_units,\n",
    "\n",
    "           'fc_activation':opt.fc_activation,\n",
    "           'optimizer':opt.optimizer}\n",
    "\n",
    "    model = lstm_model(**param)\n",
    "    y_test_pred = model.predict([X_test,X_test_biofeat])\n",
    "    evaluation = mean_squared_error(y_test, y_test_pred)\n",
    "    logger.info('----------')\n",
    "    logger.info('params:{}'.format(param))\n",
    "    logger.info('metrics——mse:{},spearman:{}'.format(evaluation,sp.stats.spearmanr(y_test, y_test_pred)[0]))\n",
    "    return evaluation"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "#time consuming \n",
    "#set initial_design_numdata and  max_iter as lower integer to reduce searching time\n",
    "opt_model = GPyOpt.methods.BayesianOptimization(f=f, domain=bounds, initial_design_numdata=30)\n",
    "opt_model.run_optimization(max_iter = 300)\n",
    "logger.info(\"optimized loss: {0}\".format(opt_model.fx_opt))\n",
    "for i,v in enumerate(bounds):\n",
    "    name = v['name']\n",
    "    logger.info('parameter {}:{}'.format(name,opt_model.x_opt[i]))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python3(crispr)",
   "language": "python",
   "name": "crispr"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.6.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
